project_id = "qmeneridwgiavindzoht"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[edge_runtime]
enabled = true
port = 8081
inspector_port = 8083

[auth]
enabled = true
site_url = "https://3000-firebase-my-receipt-insight-1765033265736.cluster-dbvlwdg2xjd32ramv3nu373xpy.cloudworkstations.dev/?embedded=0&monospaceUid=311369"
additional_redirect_urls = ["https://3000-firebase-my-receipt-insight-1765033265736.cluster-dbvlwdg2xjd32ramv3nu373xpy.cloudworkstations.dev/?embedded=0&monospaceUid=311369", "https://*.googleusercontent.com/*"]
jwt_expiry = 3600

[auth.email]
enable_signup = true

[storage]
enabled = true
file_size_limit = "50MiB"

[realtime]
enabled = true

[analytics]
enabled = false

[functions.process-receipt-ocr]
verify_jwt = false

[functions.enrich-product]
verify_jwt = false